version: '3.9'

services:
  dataDb:
    image: mysql:8.0.21
    container_name: "mysql_db"
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123456789'
      MYSQL_DATABASE: 'db_users'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456789'
    restart: 'always'
