version: '3.9'

services:
  dataDb:
    image: mysql:8.0.21
    container_name: "mysql_db"
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=997366918
    restart: 'always'
